export const GET_ALL_EXPERIENCES_SUCCESS = 'GET_ALL_EXPERIENCES_SUCCESS';
export const GET_ALL_YOUR_EXPERIENCES_SUCCESS =
  'GET_ALL_YOUR_EXPERIENCES_SUCCESS';
export const LOADING = 'LOADING';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_MOST_POPULAR_EXPERIENCES_SUCCESS =
  'GET_MOST_POPULAR_EXPERIENCES_SUCCESS';
export const GET_MOST_LIKED_EXPERIENCES_SUCCESS =
  'GET_MOST_LIKED_EXPERIENCES_SUCCESS';
export const GET_MOST_COMMENTED_EXPERIENCES_SUCCESS =
  'GET_MOST_COMMENTED_EXPERIENCES_SUCCESS';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_EXPERIENCE_SUCCESS = 'GET_EXPERIENCE_SUCCESS';
